### ISSUE TITLE
Can't get place relations

### ISSUE THREAD

**Issue by zzx0921** [ropenscilabs/mregions#51]
When I tried to get place relations by `mr_place_relations()`, I found out that `type = c("partof", "partlypartof", "adjacentto", "similarto", "administrativepartof",
    "influencedby", "all")` didn't work.
I get exactly the same results by `mr_place_relations(307, type = "adjacentto")` and `mr_place_relations(307)`
even if the default value for `type` should be "partof".

**Comment by LennertSchepers** [comment]
Hi @zzx0921, thanks for the feedback.
You are correct, it seems that the 'type' argument does not always work.

This is actually only the case for 'adjacentto', and it seems that this occurs because ithere is a typo in the REST api : the type is actually defined as 'adjecentto', see <https://marineregions.org/gazetteer.php?p=webservices&type=rest#!/getGazetteerRelationsByMRGID/Array>.

If you provide a {type} that is not recognised, the service will take by default the type 'partof', therefore it your result is the same.

I will report this and come back with any updates

**Comment by LennertSchepers** [comment]
The issue with the web service has been fixed.

There is still a small issue with the package so not closing this issue:
`mr_place_relations(307, type = "adjacentto")` sends this get request:
`http://marineregions.org/rest/getGazetteerRelationsByMRGID.json/307/upper/adjacentto"`,

but this should be
`http://marineregions.org/rest/getGazetteerRelationsByMRGID.json/307/upper/adjacentto/"`
(including the last '**/**')

**Comment by salvafern** [comment]
Hi, I will close this issue following [rOpenSci guidance on archiving packages](https://devguide.ropensci.org/maintenance_evolution.html#archivalguidance)

This repository has been archived and it is replaced by [mregions2](https://docs.ropensci.org/mregions2/). For further details please see: [Why mregions and mregions2?](https://docs.ropensci.org/mregions2/articles/why_mregions2.html).
