### ISSUE TITLE
mregions maintainer change

### ISSUE THREAD

**Issue by LennertSchepers** [ropenscilabs/mregions#61]
Hi all

I've created this issue to let you know that I'm transferring my maintainer role to @salvafern. Salva is working in our Marine Regions team and is much more capable of maintaining than me R packages, he has for example taken over maintenance over the [sdmpredictors (Bio-Oracle)](https://github.com/lifewatch/sdmpredictors) package and the [lwdataexplorer](https://github.com/lifewatch/lwdataexplorer) package, and is working with @tomjwebb @annakrystalli and @maelle on the EMODNet Biology data products.

@salvafern see https://devguide.ropensci.org/changing-maintainers.html for a nice overview of steps to take over the maintenance.

Lastly, we do plan some ✨ significant improvements ✨ to the package in the coming months, but you'll hear more about that from @salvafern!

Cheers
Lennert

**Comment by salvafern** [comment]
Maintainer changed in https://github.com/ropensci/mregions/commit/e5fb45be93a957e4ccc51158bb900f72dbcd08a1 :ok_hand:  Looking forward to work on this package!

I will create a draft pull request with all the changes that we are planning. 

We would like to have some feedback from @ropensci about our development plan before start writing code. @annakrystalli @maelle do you know if we can ask someone to do so? Maybe @sckott since he developed the package? We are planning to update the major version - i.e. deprecate functions.

Thanks!

**Comment by sckott** [comment]
Thanks for taking over @salvafern ! I've moved on to a new job and don't have time but perhaps Anna or Maëlle may have an idea

**Comment by maelle** [comment]
If you post in an issue or on discuss.ropensci.org I can have a quick look, and you could mention your questions in the #package-maintenance slack channel! :smile_cat:

**Comment by salvafern** [comment]
Done: https://discuss.ropensci.org/t/resubmit-a-package-after-a-major-update-mregions/2843

Thanks @maelle !
