### ISSUE TITLE
rgdal, rgeos archived

### ISSUE THREAD

**Issue by rsbivand** [ropenscilabs/mregions#67]
@sckott rgdal and rgeos were archived yesterday, so please do move to submit an updated version of mregions as soon as possible. See https://github.com/r-spatial/evolution https://r-spatial.github.io/evolution/ for details.

**Comment by silasprincipe** [comment]
Related to this, I just noted that the function `mr_shp` asks for `rgdal` due to this piece using `check4pkg("rgdal")`:

```
 if (read) {
    check4pkg("rgdal")
    nm <- basename(sub("\\.zip", "", file))
```

But the underlying function `read_shp` was already adapted to `sf`. Probably the package checking can already be dismissed (I did some tests here and it works fine).

**Comment by rsbivand** [comment]
I think it should be `check4pkg("sf")`, shouldn't it? No uncommented mention of `rgdal` is safe, and will mislead others reading the code.

**Comment by salvafern** [comment]
Hi @rsbivand thank you for the heads-up. This issue is not forgotten, but I got to give priority other tasks. I will tackle this as soon as I find some time. 

This said: @silasprincipe feel free to PR, I will approve if it passes the R-CMD-Check.

In the meantime (for anyone interested in this package), note that we have submitted [`mregions2`](https://github.com/lifewatch/mregions2) to rOpenSci, a major update in the form of a second package to read Marine Regions (See https://github.com/ropensci/software-review/issues/590). Our intention is to continue supporting `mregions` but do not add major updates. I recommend everyone to switch to `mregions2`.
